INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('01', 'Operação tributável: base de cálculo = valor da operação (alíquota normal – cumulativo/não cumulativo)', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('02', 'Operação tributável: base de cálculo = valor da operação (alíquota diferenciada)', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('03', 'Operação tributável: base de cálculo = quantidade vendida × alíquota por unidade de produto', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('04', 'Operação Tributável Monofásica – Revenda a Alíquota Zero', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('05', 'Operação Tributável por Substituição Tributária', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('06', 'Operação Tributável a Alíquota Zero', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('07', 'Operação Isenta da Contribuição', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('08', 'Operação sem Incidência da Contribuição', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('09', 'Operação com Suspensão da Contribuição', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('49', 'Outras Operações de Saída', 'S');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('50', 'Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Tributada no Mercado Interno', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('51', 'Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('52', 'Operação com Direito a Crédito – Vinculada Exclusivamente a Receita de Exportação', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('53', 'Operação com Direito a Crédito – Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('54', 'Operação com Direito a Crédito – Vinculada a Receitas Tributadas no Mercado Interno e de Exportação', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('55', 'Operação com Direito a Crédito – Vinculada a Receitas Não Tributadas Mercado Interno e de Exportação', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('56', 'Oper. c/ Direito a Créd. Vinculada a Rec. Tributadas e Não-Tributadas Mercado Interno e de Exportação', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('60', 'Crédito Presumido – Oper. de Aquisição Vinculada Exclusivamente a Rec. Tributada no Mercado Interno', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('61', 'Créd. Presumido – Oper. de Aquisição Vinculada Exclusivamente a Rec. Não-Tributada Mercado Interno', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('62', 'Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('63', 'Créd. Presumido – Oper. de Aquisição Vinculada a Rec.Tributadas e Não-Tributadas no Mercado Interno', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('64', 'Créd. Presumido – Oper. de Aquisição Vinculada a Rec. Tributadas no Mercado Interno e de Exportação', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('65', 'Créd. Presumido – Oper. de Aquisição Vinculada a Rec. Não-Tributadas Mercado Interno e Exportação', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('66', 'Créd. Presumido – Oper. de Aquisição Vinculada a Rec. Trib. e Não-Trib. Mercado Interno e Exportação', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('67', 'Crédito Presumido – Outras Operações', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('70', 'Operação de Aquisição sem Direito a Crédito', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('71', 'Operação de Aquisição com Isenção', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('72', 'Operação de Aquisição com Suspensão', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('73', 'Operação de Aquisição a Alíquota Zero', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('74', 'Operação de Aquisição sem Incidência da Contribuição', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('75', 'Operação de Aquisição por Substituição Tributária', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('98', 'Outras Operações de Entrada', 'E');
INSERT INTO `cst_piscofins` (`codcstpiscofins`, `descricao`, `tipomov`) VALUES ('99', 'Outras Operações', 'E');
