/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `sub_setores_bolsa` DISABLE KEYS */;
INSERT INTO `sub_setores_bolsa` (`id`, `name`) VALUES
	(1, 'Incorporações'),
	(2, 'Incorporações'),
	(3, 'Serv.Méd.Hospit. Análises e Diagnósticos'),
	(4, 'Outros'),
	(5, 'Exploração de Imóveis'),
	(6, 'Programas e Serviços'),
	(7, 'Produtos Diversos'),
	(8, 'Energia Elétrica'),
	(9, 'Máq. e Equip. Industriais'),
	(10, 'Bancos'),
	(11, 'Viagens e Turismo'),
	(12, 'Exploração de Rodovias'),
	(13, 'Transporte Hidroviário'),
	(14, 'Petroquímicos'),
	(15, 'Serviços de Apoio e Armazenagem'),
	(16, 'Publicidade e Propaganda'),
	(17, 'Telecomunicações'),
	(18, 'Computadores e Equipamentos'),
	(19, 'Água e Saneamento'),
	(20, 'Equipamentos e Serviços'),
	(21, 'Fios e Tecidos'),
	(22, 'Serviços Educacionais'),
	(23, 'Atividades Esportivas'),
	(24, 'Transporte Aéreo'),
	(25, 'Engenharia Consultiva'),
	(26, 'Material Aeronáutico e de Defesa'),
	(27, 'Serviços Diversos'),
	(28, 'Medicamentos e Outros Produtos'),
	(29, 'Agricultura'),
	(30, 'Restaurante e Similares'),
	(31, 'Alimentos Diversos'),
	(32, 'Produção de Eventos e Shows'),
	(33, 'Papel e Celulose'),
	(34, 'Eletrodomésticos'),
	(35, 'Seguradoras'),
	(36, 'Tecidos, Vestuário e Calçados'),
	(37, 'Artefatos de Ferro e Aço'),
	(38, 'Brinquedos e Jogos'),
	(39, 'Vestuário'),
	(40, 'Artefatos de Cobre'),
	(41, 'Minerais Metálicos'),
	(42, 'Exploração, Refino e Distribuição'),
	(43, 'Automóveis e Motocicletas'),
	(44, 'Carnes e Derivados'),
	(45, 'Hotelaria'),
	(46, 'Intermediação Imobiliária'),
	(47, 'Embalagens'),
	(48, 'Material Rodoviário'),
	(49, 'Materiais Diversos'),
	(50, 'Utensílios Domésticos'),
	(51, 'Aluguel de carros'),
	(52, 'Produtos para Construção'),
	(53, 'Serviços Financeiros Diversos'),
	(54, 'Programas de Fidelização'),
	(55, 'Corretoras de Seguros'),
	(56, 'Acessórios'),
	(57, 'Material de Transporte'),
	(58, 'Alimentos'),
	(59, 'Holdings Diversificadas'),
	(60, 'Produtos de Limpeza'),
	(61, 'Construção Pesada'),
	(62, 'Siderurgia'),
	(63, 'Madeira'),
	(64, 'Gestão de Recursos e Investimentos'),
	(65, 'Armas e Munições'),
	(66, 'Calçados'),
	(67, 'Máq. e Equip. Construção e Agrícolas'),
	(68, 'Fertilizantes e Defensivos'),
	(69, 'Químicos Diversos'),
	(70, 'Transporte Ferroviário'),
	(71, 'Açucar e Alcool'),
	(72, 'Motores, Compressores e Outros'),
	(73, 'Soc. Crédito e Financiamento'),
	(74, 'Transporte Rodoviário'),
	(75, 'Gás'),
	(76, 'Móveis'),
	(77, 'Cervejas e Refrigerantes'),
	(78, 'Equipamentos'),
	(79, 'Bicicletas'),
	(80, 'Produtos de Uso Pessoal');
/*!40000 ALTER TABLE `sub_setores_bolsa` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
