INSERT INTO segmentos_cest VALUES (1, 'Autopeças', '01');
INSERT INTO segmentos_cest VALUES (2, 'Bebidas alcoólicas, exceto cerveja e chope', '02');
INSERT INTO segmentos_cest VALUES (3, 'Cervejas, chopes, refrigerantes, águas e outras bebidas', '03');
INSERT INTO segmentos_cest VALUES (4, 'Cigarros e outros produtos derivados do fumo', '04');
INSERT INTO segmentos_cest VALUES (5, 'Cimentos', '05');
INSERT INTO segmentos_cest VALUES (6, 'Combustíveis e lubrificantes', '06');
INSERT INTO segmentos_cest VALUES (7, 'Energia elétrica', '07');
INSERT INTO segmentos_cest VALUES (8, 'Ferramentas', '08');
INSERT INTO segmentos_cest VALUES (9, 'Lâmpadas, reatores e “starter”', '09');
INSERT INTO segmentos_cest VALUES (10, 'Materiais de construção e congêneres', '10');
INSERT INTO segmentos_cest VALUES (11, 'Materiais de limpeza', '11');
INSERT INTO segmentos_cest VALUES (12, 'Materiais elétricos', '12');
INSERT INTO segmentos_cest VALUES (13, 'Medicamentos de uso humano e outros produtos farmacêuticos para uso humano ou veterinário', '13');
INSERT INTO segmentos_cest VALUES (14, 'Papéis, plásticos, produtos cerâmicos e vidros', '14');
INSERT INTO segmentos_cest VALUES (16, 'Pneumáticos, câmaras de ar e protetores de borracha', '16');
INSERT INTO segmentos_cest VALUES (17, 'Produtos alimentícios', '17');
INSERT INTO segmentos_cest VALUES (19, 'Produtos de papelaria', '19');
INSERT INTO segmentos_cest VALUES (20, 'Produtos de perfumaria e de higiene pessoal e cosméticos', '20');
INSERT INTO segmentos_cest VALUES (21, 'Produtos eletrônicos, eletroeletrônicos e eletrodomésticos', '21');
INSERT INTO segmentos_cest VALUES (22, 'Rações para animais domésticos', '22');
INSERT INTO segmentos_cest VALUES (23, 'Sorvetes e preparados para fabricação de sorvetes em máquinas', '23');
INSERT INTO segmentos_cest VALUES (24, 'Tintas e vernizes', '24');
INSERT INTO segmentos_cest VALUES (25, 'Veículos automotores', '25');
INSERT INTO segmentos_cest VALUES (26, 'Veículos de duas e três rodas motorizados', '26');
INSERT INTO segmentos_cest VALUES (28, 'Venda de mercadorias pelo sistema porta a porta', '28');
