INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('00', 'Tributada integralmente', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('10', 'Tributada e com cobrança do ICMS por substituição tributária', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('101', 'Tributada pelo Simples Nacional com permissão de crédito', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('102', 'Tributada pelo Simples Nacional sem permissão de crédito', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('103', 'Isenção do ICMS no Simples Nacional para faixa de receita bruta', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('20', 'Com redução da BC', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('201', 'Tributada pelo Simples Nacional com permissão de crédito e com cobrança de ICMS por ST', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('202', 'Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por substituição tributária', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('203', 'Isenção do ICMS no Simples Nacional para faixa de receita bruta e com cobrança do ICMS por substituição tributária', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('30', 'Isenta / não tributada e com cobrança do ICMS por substituição tributária', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('300', 'Imune', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('40', 'Isenta', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('400', 'Não tributada pelo Simples Nacional', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('41', 'Não tributada', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('50', 'Com suspensão', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('500', 'ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação', 'S');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('51', 'Com diferimento', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('60', 'ICMS cobrado anteriormente por substituição tributária', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('70', 'Com redução da BC e cobrança do ICMS por substituição tributária', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('90', 'Outras', 'N');
INSERT INTO `cst_icms` (`codcsticms`, `descricao`, `optantesimplesnacional`) VALUES ('900', 'Outros', 'S');